### ISSUE TITLE
Warp transformation

### ISSUE THREAD

**Issue by anjaliagarwal8** [Xilinx/xfopencv#11]
Hi,
I wanted to use warp transformation functions of xfOpenCV: warpaffine and warpperspective.
But in the header files, there are two options for it. In the warptransform, there is a option to do these transformations and also there are separate warpaffine and warpperspective functions in the include folder. What is the difference between them?

**Comment by bgouthamb** [comment]
@Anjali-iit8 
Warpaffine and Warpperspective are memory mapped implementations, whereas Warptransform is a streaming implementation. Functionally both are similar. For pipeline applications, Warptransform is more suitable.

**Comment by anjaliagarwal8** [comment]
@bgouthamb 
Can I also perform inverse warpAffine and inverse warpPerspective using warptransform because I cannot see any parameter for specifying it, like in OpenCV we give the flag WARP_INVERSE_MAP

**Comment by bgouthamb** [comment]
@Anjali-iit8 
Yes, you can. There is no flag to set, you yourself need to generate and provide the inversed transformation matrix instead.

**Comment by anjaliagarwal8** [comment]
Okay. Thankyou

**Comment by bgouthamb** [comment]
@Anjali-iit8 
Please close the issue if you think your question is answered.

**Comment by LIFM6** [comment]
Hello, may I ask how you encapsulated the warp view function into an IP core? Can you teach me?
