### ISSUE TITLE
Will the functions SGBM and HoughLines work in SDx 2017.4?

### ISSUE THREAD

**Issue by pedrombmachado** [Xilinx/xfopencv#15]
Dear support.
   I have a question that I would like to post before installing the SDx 2017.4 or 2018.2. Most of our work is done on v.2017.4 and therefore I would like to know if the SGBM and HoughLines work in SDx 2017.4?
Many thanks,
Pedro

**Comment by bgouthamb** [comment]
Hello @pedrombmachado ,
SGBM and HoughLines were developed and tested for 2018.2. So, we recommend using 2018.2 SDx for those two functions.

**Comment by pedrombmachado** [comment]
Hi @bgouthamb ,
  Many thanks for the clarification.
Bw
Pedro
