### ISSUE TITLE
Is there rules in using xfOpenCV in Sdx ?

### ISSUE THREAD

**Issue by tangjie77wd** [Xilinx/xfopencv#19]
Hello , i have succeeded in building xfOpenCV/example/dilation in zedboard7020 in Sdx 2018.2 ! And now i am trying to build my own project just changing from xfOpenCV/example/dilation --
`
#include "xf_dilation_config.h"
#pragma SDS data access_pattern("_src.data":SEQUENTIAL, "_dst.data":SEQUENTIAL)
#pragma SDS data copy("_src.data"[0:"_src.size"], "_dst.data"[0:"_dst.size"])
#pragma SDS data mem_attribute("_src.data":NON_CACHEABLE|PHYSICAL_CONTIGUOUS)
#pragma SDS data mem_attribute("_dst.data":NON_CACHEABLE|PHYSICAL_CONTIGUOUS)
void dilation_accel(xf::Mat<TYPE, HEIGHT, WIDTH, NPC1> &_src,xf::Mat<TYPE, HEIGHT, WIDTH, NPC1> &_dst)
{
	xf::Mat<TYPE, HEIGHT, WIDTH, NPC1> img2;
	xf::Mat<TYPE, HEIGHT, WIDTH, NPC1> img3;

	xf::Threshold<XF_THRESHOLD_TYPE_BINARY,XF_8UC1,HEIGHT, WIDTH,NPC1>(_src,img2,30,255,0);
	xf::dilate<XF_BORDER_CONSTANT,TYPE ,HEIGHT, WIDTH,NPC1>(img2, img3);
	xf::erode<XF_BORDER_CONSTANT,TYPE ,HEIGHT, WIDTH,NPC1>(img3,_dst);
}
`

What i have changed is that adding xf::Threshold and xf::erode to the top function , does which break the rule in using xfOpenCV ? This new project has been building from yesterday to now ! However,building failed with the following error information:
ERROR: [VPL 8-5834] Design needs 4581 RAMB18 which is more than device capacity of 280
ERROR: [VPL 17-69] Command failed: Vivado Synthesis failed
ERROR: [VPL 60-704] Integration error, One or more synthesis runs failed during dynamic region dcp generation
ERROR: [VPL 60-806] Failed to finish platform linker
I really do not know what's going on ! I just appended xf::Threshold and xf::erosion to the primary function !

**Comment by tangjie77wd** [comment]
solved!!

**Comment by swordwest** [comment]
>           solved!!

How do you solve this problem?
