### ISSUE TITLE
When I xf_median_blur example，I meet this error!

### ISSUE THREAD

**Issue by 444903935** [Xilinx/xfopencv#26]
INFO: [DMAnalysis 83-4494] Analyzing hardware accelerators...
ERROR: [DMAnalysis 83-4432] An unsupported inferred interface type (ap_memory) was detected 
for the port p_src_data_V_q0 (name maybe encoded) of accelerator median_blur_accel. Near D:/WZZ/SDx_workspace/xf_opencv_medianblur/src/xf_median_blur_accel.cpp:32
  [SUGGESTION]: Please check the argument declaration.  For array, we recommend linearized array type
  or pointer type enhanced with pragmas as needed.  Please refer to documentation on Pragma SDS data.
Data motion generation exited with return code 1
- errors detected
sds++ log file saved as D:/WZZ/SDx_workspace/xf_opencv_medianblur/Release/_sds/reports/sds.log
ERROR: [SdsCompiler 83-5004] Build failed

How can I solve it？Thanks.

**Comment by bgouthamb** [comment]
Please check the function you have marked for hardware acceleration.  "median_blur_accel" is a wrapper function.  "xf::medianBlur" is the function to be moved to hardware.

**Comment by 444903935** [comment]
The problem now is that I can't find "xf::medianBlur". And I found that I can't add the xfopencv library to the include. I have set the xfopencv library path in the C++ Build Setting->SDS++ Compiler-> Directories.The value is "D:/WZZ/xfopencv-master/include". I am sure the path I added is correct.

**Comment by 444903935** [comment]
OK now! Thanks. I find "xf::medianBlur" in "lib" instead of "include".
