### ISSUE TITLE
SDx2017.4 error

### ISSUE THREAD

**Issue by xianghan228** [Xilinx/xfopencv#3]
^
/opt/Xilinx/SDx/2017.4/platforms/zcu102_es2_rv_ss/sw/a53_linux/inc/xfopencv/common/xf_sw_utils.h:121:98: error: type name requires a specifier or qualifier
/opt/Xilinx/SDx/2017.4/platforms/zcu102_es2_rv_ss/sw/a53_linux/inc/xfopencv/common/xf_sw_utils.h:121:98: error: expected unqualified-id
/opt/Xilinx/SDx/2017.4/platforms/zcu102_es2_rv_ss/sw/a53_linux/inc/xfopencv/common/xf_sw_utils.h:122:88: error: expected '>'
     diff_img.at<ap_uint<PixelType<DataType<_PTYPE,_NPC>::pixeldepth>::bitdepth>>(i,j) = abs(cv_pix - xf_pix.range(shift+STEP-1, shift));

**Comment by bgouthamb** [comment]
Unable to replicate this error. Could you please provide more details? The function you tried to build, OS, paths, and flags in Makefile etc..
