### ISSUE TITLE
How can I do pixel-wise computation with a xf:Mat ?

### ISSUE THREAD

**Issue by microlijun** [Xilinx/xfopencv#30]
xf::Mat<XF_8UC1, HEIGHT, WIDTH, XF_NPPC1> a;
xf::Mat<XF_8UC1, HEIGHT, WIDTH, XF_NPPC1> b;
xf::Mat<XF_8UC1, HEIGHT, WIDTH, XF_NPPC1> c;
c(x,y)=a(x,y)/b(x,y)
How can I get c by using xfOpenCv???
In OpenCv, I can directly do a/b, but xfOpenCv do not have pixel-wize division function. I tried to define a division function by myself.
	for (int i = 0; i < HEIGHT; i++)
				for (int j = 0; j < WIDTH; j++)
				{
					c[i][j] = a[i][j]/b[i][j];
				}
but I got error: '[]' could not be resolved
So how can I do pixel-wise computation with a xf:Mat ? 
Could you give an example?

**Comment by bgouthamb** [comment]
@microlijun 
You need to use the '.data' pointer to access each pixel value of an xf::Mat object.
```
for (int i = 0; i < HEIGHT; i++){
     for (int j = 0; j < WIDTH; j++){
          c.data[i*WIDTH+j] = a.data[i*WIDTH+j] / b.data[i*WIDTH+j];
    }
 }
```

To know how to optimize the above implementation, have a look at anyone of the [arithm ](https://github.com/Xilinx/xfopencv/blob/975fbb9255b72769f05f75ffbed994b4e7e4c3a9/include/core/xf_arithm.hpp#L458) functions.
