### ISSUE TITLE
bad track status return by xf::MeanShift

### ISSUE THREAD

**Issue by yinedeng** [Xilinx/xfopencv#35]
hi @bgouthamb ,
   When I used meanshifttracking example without any code change, I get a problem.

   First, I start meanshifttracking with image in data directory. It looks runs well.

   But, I want to have a see what will happend if the frame are not consecutive. 

   So, I rename img101.png as img5.png to do that.

   the result,  the new frame 5 have the same result as frame 4. it tells me it still tracking, but the fact is not

**Comment by bgouthamb** [comment]
Hello @yinedeng ,

I'm assuming you are deducing whether the object is getting tracked or not, depending on the value of the function parameter 'status'. As it is mentioned in UG1233 doc, the function parameter 'status' gives out the information whether the given object is within the current frame or not. It is not meant to provide the info if the object has been successfully tracked.

Anyways, in a practical scenario, an object will not disappear completely in the immediate frame.  So, such a case has not been considered during implementation.
