### ISSUE TITLE
C Synthesis error of xf_histogram

### ISSUE THREAD

**Issue by microlijun** [Xilinx/xfopencv#40]
Hi, 
I am migrating my opencv application to xfopencv. The C Simulation passed but I got error when run C Synthesis.

ERROR: [SYNCHK 200-61] /home/jun/WorkSpace2/xfopencv/include/imgproc/xf_histogram.hpp:169: unsupported memory access on variable 'histogram' which is (or contains) an array with unknown size at compile time.

xf::calcHist is used, that might be the problem.  How can I solve this problem?

**Comment by bgouthamb** [comment]
Hello @microlijun ,

The argument 'histogram' in the _calcHist()_ API is a pointer with no info of its size. For Standalone HLS Synthesis, the _m_axi_ HLS interface pragma needs to be declared for such arguments. See point no.3 on page 3 of [HLS Use Model Doc](https://github.com/Xilinx/xfopencv/blob/master/HLS_Use_Model/HLS_UseModel_Usage_Doc.pdf).
