### ISSUE TITLE
imgproc库中缺少xf::crop 函数

### ISSUE THREAD

**Issue by userofyour** [Xilinx/xfopencv#43]

**Comment by userofyour** [comment]
The xf::crop function is missing from the imgproc library.I could not find this function.But I saw this function in the UG1223.
I want to calculate the local entropy of image ,so I want to use the function about calcHist and crop in xfopencv lib.

**Comment by bgouthamb** [comment]
Hi @userofyour,

Actually, that is a documentation error in UG1233. The function "Crop" will be available in the next release.

**Comment by bgouthamb** [comment]
Crop function is now available in 2019.1 release.

**Comment by userofyour** [comment]
That's cool！Thanks!

------------------ 原始邮件 ------------------
发件人: "Goutham Borra"<notifications@github.com>;
发送时间: 2019年6月18日(星期二) 中午1:50
收件人: "Xilinx/xfopencv"<xfopencv@noreply.github.com>;
抄送: "330526937"<330526937@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Xilinx/xfopencv] imgproc库中缺少xf::crop 函数 (#43)




Crop function is now available in 2019.1 release.
