### ISSUE TITLE
How to program the board to run xfopencv application?

### ISSUE THREAD

**Issue by microlijun** [Xilinx/xfopencv#44]
Hi, I'm migrating an OpenCV application to xfOpenCV.  I already got SD Card image with SDSoC environment. It should be program the board through SD card. But In my lab, FPGA boards are set up on server, Ubuntu are running on ARM. In that case, what should I do with the SD Card image files?

**Comment by bgouthamb** [comment]
@microlijun This question should go on the [forum](https://forums.xilinx.com/t5/SDSoC-Environment-and-reVISION/bd-p/sdsoc). You can get the required help there.
