### ISSUE TITLE
ERROR: [SYNCHK 200-71] function 'lround' has no function body.

### ISSUE THREAD

**Issue by 3togo** [Xilinx/xfopencv#52]
Any hints to fix this error?

ERROR: [SYNCHK 200-71] ../xfopencv/xfopencv-2018.3_release/include/common/xf_structs.h:503: function 'lround' has no function body.

**Comment by bgouthamb** [comment]
@3togo 
'lround' is a standard C++ function, which cannot be synthesized. The _xf::Mat_ member function _convertTo_ is meant to be used only on the host side. The synthesizable _convertTo_ function is available at _include/imgproc/xf_convert_bitdepth.hpp_

**Comment by 3togo** [comment]
do you mean that xf::Mat has two versions? One is for host side and the other is for the synthetic side.

**Comment by 3togo** [comment]
How to do something similar to below
xf::convertTo<XF_16UC1, XF_8UC1, src_rows, src_cols, XF_NPPC1> (dst16, dst, XF_CONVERT_16U_TO_8U, 0);

that can be synthesized?

**Comment by bgouthamb** [comment]
xf::convertTo<XF_16UC1, XF_8UC1, src_rows, src_cols, XF_NPPC1> (dst16, dst, XF_CONVERT_16U_TO_8U, 0);

This indeed is the synthesizable function. Are you getting the issue with 'lround' when synthesizing the above function? What is the SDx tool version you use?

**Comment by 3togo** [comment]
I am using it in bare HLS. It is not synthesizable using Vivado 2019.1 and 2018.3

**Comment by bgouthamb** [comment]
@3togo 
Can you post the log file, along with the source file where you are calling this function?

**Comment by 3togo** [comment]
better focus on 2019.1 version instead
