### ISSUE TITLE
compatibility of xfopencv with vivado 

### ISSUE THREAD

**Issue by 3togo** [Xilinx/xfopencv#54]
I think xf_opencv requires an external version of opencv. When doing hls synthesis, I guess it will be using the following opencv include folder
/tools/Xilinx/Vivado/2018.3/include/opencv2/

My question is whether this version of opencv is compatible with xfopencv 2018.3

Eli

**Comment by bgouthamb** [comment]
@3togo 
OpenCV files are not supposed to be synthesized.  All the OpenCV functions are to be used on the testbench (host side) and only for Simulation and Co-Simulation purposes.

**Comment by 3togo** [comment]
bgouthamb,

Many thanks. Problem Solved.
