### ISSUE TITLE
Will xfopencv support Artix-7 in near future?

### ISSUE THREAD

**Issue by 3togo** [Xilinx/xfopencv#67]
I am now planning to tailor-make a fpga board for high performance TV. I wonder whether I could use xfopencv with Atrix-7 because it is relatively cheaper than zynq series.

According to your web site,
"The xfOpenCV library is designed to work with Zynq, Zynq Ultrascale+, and Alveo FPGAs. The library has been verified on zcu102, zcu104 and U200 boards."

**Comment by bgouthamb** [comment]
Hello @3togo ,

xfOpenCV is like any other HLS optimized C++ functions. It can be built for any FPGA, provided that:
 1. The FPGA has enough resources to fit the implemented function. The total resources consumed 
 would in turn affects the max. frequency of operation.
2. You got the required platform to support the build (I don't see Artix in SDx) or You take care of programming the FPGA on your own through Vivado.

You might want to take a look at Ultra96 available at comparatively lower cost.

**Comment by 3togo** [comment]
Many thanks
