### ISSUE TITLE
how to drain unused xf::Mat in HLS?

### ISSUE THREAD

**Issue by 3togo** [Xilinx/xfopencv#68]
I only need to process _dst_matx.   As a result _dst_maty will never be used, I wonder what is the proper to drain xf::Mat?

void Sobel(xf::Mat<SRC_T, ROWS, COLS, NPC> & _src_mat,xf::Mat<DST_T, ROWS, COLS, NPC> & _dst_matx,xf::Mat<DST_T, ROWS, COLS, NPC> & _dst_maty)

**Comment by bgouthamb** [comment]
@3togo 
You can simply readout the Mat that you do not wish to process.

**Comment by 3togo** [comment]
many thanks
