### ISSUE TITLE
New project

### ISSUE THREAD

**Issue by anjaliagarwal8** [Xilinx/xfopencv#7]
Hi,
I have a project involving image processing and neural networks which I want to port to Xilinx platform zcu104_rv_ss. It was made using LeNet and I have successfully got the executable file for the same. Now I have a main code for which I want to get the elf file. Can you help me with that as I am unable to find any documentation regarding that.

Thanks,
Anjali

**Comment by bgouthamb** [comment]
This doesn't seem to qualify as an issue. Please post this in the Xilinx SDSoC forum to get the needed help.
