### ISSUE TITLE
how to trim the output from pyrDown?

### ISSUE THREAD

**Issue by 3togo** [Xilinx/xfopencv#73]
xf::pyrDown<XF_8UC1, src_rows, src_cols, NPC, XF_USE_URAM> (src, src2);

src and src2 should be of the same size (src_rows, src_cols)
However, pyrDown should reduce the size of src2 to ((src_rows+1)/2, (src_cols+1)/2).

My problem is how to "resize" src2 to ((src_rows+1)/2, (src_cols+1)/2)?

Thank in advance for any advice.

**Comment by 3togo** [comment]
no need to resize

**Comment by Anadelphia** [comment]
Hi 
It’s not clear, why I can’t define the _dst size smaller ( _src.size/2) than _src because by  pyramid downing the image, we want to decreases image size. But we are defining _dst size same as _src
